### ISSUE TITLE
Handle option calls or CORS request

### ISSUE THREAD

**Issue by novomanish** [biesiad/deelay#3]
The server does not handle CORS pre-flight request and returns 404 which breaks the flow. The deelay server should handle cors requests.

**Comment by biesiad** [comment]
@novomanish this should be fixed in v1.0.4

https://github.com/biesiad/deelay/commit/809cbc8079441d9d6b5a9d43a827548f3714a7c0#diff-168726dbe96b3ce427e7fedce31bb0bcR22

**Comment by biesiad** [comment]
I still have to update the website, which is using old ruby gem. I'll keep the issue open.

**Comment by acarnwath** [comment]
Is there an ETA on when the website will be updated? I love this service but this is a blocker for almost all of my use cases..

**Comment by biesiad** [comment]
@acarnwath I'm sorry to hear that. There's no ETA unfortunately. For the time being, I encourage you to use the local instance of the server.

**Comment by biesiad** [comment]
Migrated to node implementation which supports CORS and just tested, it's working now. Make sure the server you're redirecting to also returns CORS headers.
