### ISSUE TITLE
ERR_CERT_COMMON_NAME_INVALID when accessing deelay.me

### ISSUE THREAD

**Issue by alex-linde** [biesiad/deelay#5]
It seems that your herokuapp has an incorrect certificate config issue
![Screen Shot 2019-05-01 at 6 13 41 pm](https://user-images.githubusercontent.com/10956179/57010674-14d7c280-6c3d-11e9-8b72-dc90cc63b3a8.png)

**Comment by dan-harris** [comment]
First up, thanks for this awesome tool! It's the only one I could find that has this kind of functionality.

For a bit of context on the above, I'm using your public service via deelay.me for some demos on this presentation; [presentations.danharris.io/web-perf](https://presentations.danharris.io/web-perf)

I get the above error when trying to use your service over https (e.g. https://deelay.me). I'm not sure if https is supported, but would be great if it could be👍

Thanks a bunch!

**Comment by biesiad** [comment]
Thanks for reminding me of this. No, https won't work. I know it's a little bit of a deal breaker, especially with how strict browsers are these days. When I published the website, the browsers didn't care very much about https. It's good to know that people actually want to use it. That should help me with finding motivation and fixing it :)

Some detail about why it is _crippled_ the way it is: Heroku (where the server is hosted) doesn't go well with free certs from [let's encrypt](https://letsencrypt.org/). I started setting it up and left half way done when I realized I either need to get a proper certificate or have to change the hosting provider to use Let's Encrypt to make it work.

I'll go back to it and find a different hosting when I have some free time. Any suggestions for an inexpensive cloud to run deelay in a docker container?  I'll keep the issue open and update it when I have some updates.

**Comment by dan-harris** [comment]
Ahh, no problems. You can get a free (root) cert through AWS (if you run your docker through Amazon Elastic Container Service).... if AWS works well for you, highly recommend that as a cheap option!

**Comment by Korayem** [comment]
A much faster option is to use cloudflare flexible SSL. It allows visitors to access your site through https on Cloudflare while Cloudflare talks to your server in http

Client <https> Cloudflare <http> Your server

For more info:
https://support.cloudflare.com/hc/en-us/articles/200170416-End-to-end-HTTPS-with-Cloudflare-Part-3-SSL-options

**Comment by benswinburne** [comment]
> Some detail about why it is _crippled_ the way it is: Heroku (where the server is hosted) doesn't go well with free certs from [let's encrypt](https://letsencrypt.org/). I started setting it up and left half way done when I realized I either need to get a proper certificate or have to change the hosting provider to use Let's Encrypt to make it work.

FWIW you can use Let's Encrypt on Heroku

https://blog.heroku.com/announcing-automated-certificate-management

    heroku certs:auto:enable -a <app name>

Then update your DNS to the new target and you should be good to go.

https://devcenter.heroku.com/articles/automated-certificate-management#migrating-existing-applications

**Comment by biesiad** [comment]
I moved the app to a different hosting provider and added the certs. https is now working.
