### ISSUE TITLE
Using deelay.me will not work from HTTPS

### ISSUE THREAD

**Issue by npm1** [biesiad/deelay#6]
If you try to use an image from deelay.me in an https webpage on Chrome canary (latest chrome version available), it will not work. The DevTools console says "Mixed Content: The page at 'URL' was loaded over HTTPS, but requested an insecure element 'IMAGE'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html". The upgrade to HTTPS doesn't work, and hence the image does not display. Per the blog timeline, this will be the default on February.

**Comment by biesiad** [comment]
Added a certificate. It'll work now.
